# **ECE 2112 PA 2**

### **Submitted by: Jia Bernice C. Magcamit**

## **PROBLEM** **A**

In [2]:
import numpy as np

In [3]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))

In [4]:
x_mean = np.mean(X)
x_std = np.std(X)

In [5]:
X_normalized = (X - x_mean) / x_std

In [6]:
np.save("X_normalized.npy", X_normalized)
data = np.load("X_normalized.npy")

In [8]:
print("X: \n", X)
print("\nX_normalized: \n", data)
print("\n Mean of X_normalized: \n", X_normalized.mean())
print("\n Standard Deviation of X_normalized: \n",X_normalized.std())

X: 
 [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]

X_normalized: 
 [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]

 Mean of X_normalized: 
 0.0

 Standard Deviation of X_normalized: 
 0.9999999999999999


## **PROBLEM B**

In [10]:
integers = np.arange(1,101)
C = (integers**3).reshape(10,10)

In [11]:
div_by_4 = C[C%4 == 0]
np.save("div_by_4.npy", div_by_4)
div4 = np.load("div_by_4.npy")

In [12]:
print("Shape of C: \n", C.shape)
print("\n div_by_4: \n", div4)
print("\n Number of Selected Eleemnts: \n", div_by_4.size)

Shape of C: 
 (10, 10)

 div_by_4: 
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]

 Number of Selected Eleemnts: 
 50


### **PROBLEM C**

In [13]:
S1 = np.arange(1,37)**2
S = S1.reshape(6,6)

In [14]:
S_mean = np.mean(S)
above_mean = S[S>S_mean]
np.save("above_mean.npy", above_mean)
abvmean = np.load("above_mean.npy")

In [ ]:
print("S: \n", S)
print("\n S_mean: \n", S_mean)
print("\n above_mean: \n"abvmean)
print("\n Number \n")

[[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]
450.1666666666667
[ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]
15
